config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'cards/new'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  
  root "items#index"
  resources :items do
    resources :orders, only: [:index, :create]
    resources :comments, only: [:create]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end  
  resources :cards, only: [:new, :create]
  resources :users, only: [:show, :update]


end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :order
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user
  
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' }, { id: 1, name: 'レディース' },
    { id: 2, name: 'メンズ' }, { id: 3, name: 'ベビー・キッズ' },
    { id: 4, name: 'インテリア・住まい・小物' }, { id: 5, name: '本・音楽・ゲーム' },
    { id: 6, name: '家電・スマホ・カメラ' }, { id: 7, name: 'スポーツ・レジャー' },
    { id: 8, name: 'ハンドメイド' }, { id: 9, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/comment.rb
class Comment < ApplicationRecord
    
  belongs_to :user
  belongs_to :item

  validates :content, presence: true
  
end

app/models/condition.rb
class Condition < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' }, { id: 1, name: '新品・未使用' },
    { id: 2, name: '未使用に近い' }, { id: 3, name: '目立った傷や汚れなし' },
    { id: 4, name: 'やや傷や汚れあり' }, { id: 5, name: '傷や汚れあり' },
    { id: 6, name: '全体的に状態が悪い' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :item

  validates_uniqueness_of :item_id, scope: :user_id

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_one :order
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to_active_hash :condition
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :select_delivery_fee
  belongs_to_active_hash :term

  with_options presence: true do
    validates :images
    validates :name
    validates :description
    validates :price, numericality: { only_integer: true, message: 'は半角数字で入力して下さい' }
  end
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'が範囲外です' }

  with_options numericality: { other_than: 0, message: 'を選択して下さい' } do
    validates :category_id
    validates :condition_id
    validates :select_delivery_fee_id
    validates :prefecture_id
    validates :term_id
  end


  def self.search(search)
    if search != ""
      Item.where("name like? ", "%#{search}%")
    else
      Item.all
    end
  end

  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end
 
  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end

end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :item
  has_one :address
end

app/models/order_address.rb
class OrderAddress
  include ActiveModel::Model
  attr_accessor :postal_code, :prefecture_id, :city, :house_number, :building_name, :phone_number, :user_id, :item_id

  with_options presence: true do
    validates :postal_code, format: { with: /\A[0-9]{3}-[0-9]{4}\z/, message: 'は"-"を含めて下さい' }
    validates :city
    validates :house_number
    validates :phone_number, format: { with: /\A[0-9０-９]+\z/, message: 'は数字のみで入力して下さい' }
  end

  validates :phone_number, length: { maximum: 12 }
  validates :prefecture_id, numericality: { other_than: 0, message: 'を選択して下さい' }

  def save
    order = Order.create(item_id: item_id, user_id: user_id)
    Address.create(postal_code: postal_code, prefecture_id: prefecture_id, city: city, house_number: house_number, building_name: building_name, phone_number: phone_number, order_id: order.id)
  end
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' }, { id: 1, name: '北海道' }, { id: 2, name: '青森県' },
    { id: 3, name: '岩手県' }, { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' },
    { id: 6, name: '山形県' }, { id: 7, name: '福島県' }, { id: 8, name: '茨城県' },
    { id: 9, name: '栃木県' }, { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' },
    { id: 12, name: '千葉県' }, { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' },
    { id: 15, name: '新潟県' }, { id: 16, name: '富山県' }, { id: 17, name: '石川県' },
    { id: 18, name: '福井県' }, { id: 19, name: '山梨県' }, { id: 20, name: '長野県' },
    { id: 21, name: '岐阜県' }, { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' },
    { id: 24, name: '三重県' }, { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' },
    { id: 27, name: '大阪府' }, { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' },
    { id: 30, name: '和歌山県' }, { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' },
    { id: 33, name: '岡山県' }, { id: 34, name: '広島県' }, { id: 35, name: '山口県' },
    { id: 36, name: '徳島県' }, { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' },
    { id: 39, name: '高知県' }, { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' },
    { id: 42, name: '長崎県' }, { id: 43, name: '熊本県' }, { id: 44, name: '大分県' },
    { id: 45, name: '宮崎県' }, { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  
  belongs_to :user, optional: true

end

app/models/term.rb
class Term < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' }, { id: 1, name: '1~2日で発送' },
    { id: 2, name: '2~3日で発送' }, { id: 3, name: '4~7日で発送' }
  ]

  include ActiveHash::Associations
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  has_many :items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :sns_credentials


  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は文字と数字の両方を含めて下さい' }

  with_options presence: true do
    validates :nickname
    validates :birthday
    validates :last_name
    validates :first_name
    validates :last_name_reading
    validates :first_name_reading
  end

  with_options format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'は全角で入力して下さい' } do
    validates :last_name
    validates :first_name
  end

  with_options format: { with: /\A[ァ-ヶー－]+\z/, message: 'は全角カタカナで入力して下さい' } do
    validates :last_name_reading
    validates :first_name_reading
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Furima32521</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v1/"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://kit.fontawesome.com/b5a1381ea8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= breadcrumbs separator: " &rsaquo; " %>   
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    だれでもかんたん、人生を変えるフリマアプリ
  </p>
  <h2 class='ad-footer-title'>
    今すぐ無料ダウンロード！
  </h2>
  <div class='store-btn'>
    <%= link_to image_tag("https://linkmaker.itunes.apple.com/ja-jp/badge-lrg.svg?releaseDate=2011-09-21&kind=iossoftware&bubble=ios_apps", class:"apple-btn"), "#" %>
    <%= link_to image_tag("dl-android.png", class:"google-btn"), "#" %>
  </div>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
        <li><%= link_to 'プライバシーポリシー', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMA利用規約', "#", class: "footer-link" %></li>
        <li><%= link_to 'ポイントに関する特約', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAを見る</h2>
      <ul>
        <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
        <li><%= link_to 'ブランド一覧', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>FURIMAについて</h2>
      <ul>
        <li><%= link_to 'FURIMAガイド', "#", class: "footer-link" %></li>
        <li><%= link_to 'FURIMAロゴ利用ガイドライン', "#", class: "footer-link" %></li>
        <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("furima-logo-white.png", class:"logo-white"), "#" %>
  <p>© FURIMA</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
    <%= form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "キーワードを入力して下さい", class: "search-input" %>
      <%= f.button :type => "submit", style: 'border-style: none;' do %>
        <i class="fas fa-search-plus"></i>
      <% end %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      <li><%= link_to 'ブランド', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

<input id="menu" type="checkbox">
<label for="menu" class="open">
    <span></span>
    <span></span>
    <span></span>
</label>
<label for="menu" class="close-2"></label>
<div class="content">
  <div class="content-title">
    詳細検索
  </div>
  <%= search_form_for @p, url: search_items_path, class: "content-search-form" do |f|  %>
    <%= f.label :category_id_eq, 'カテゴリー：' %>
    <br>
    <%= f.collection_select :category_id_eq, Category.all, :id, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :condition_id_eq, '商品の状態：' %>
    <br>
    <%= f.collection_select :condition_id_eq, Condition.all, :id, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :select_delivery_fee_id_eq, '配送料の負担：' %>
    <br>
    <%= f.collection_select :select_delivery_fee_id_eq, SelectDeliveryFee.all, :id, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :prefecture_id_eq, '都道府県：' %>
    <br>
    <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :term_id_eq, '商品到達までの期間：' %>
    <br>
    <%= f.collection_select :term_id_eq, Term.all, :id, :name, include_blank: '指定なし' %>
    <br>
    <%= f.label :price, '価格：' %>
    <br>
    <%= f.radio_button :price_lteq, '' %>
    指定なし
    <br>
    <%= f.radio_button :price_lteq, '1000' %>
    1000円以下
    <br>
    <%= f.radio_button :price_lteq, '2500' %>
    2500円以下
    <br>
    <%= f.radio_button :price_lteq, '5000' %>
    5000円以下
    <br>
    <%= f.submit '検索' %>
  <% end %>
</div>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>FURIMA利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "furima-logo-color.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("furima-logo-color.png", class:"second-logo"), "/" %>
</header>